name: jbook-solarp
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - jupyter-book
    - myst-parser
    - sphinx
    - sphinx-book-theme
    - jupyter-cache
    - nbclient
